version: "3.1"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    user: '0:0'
    container_name: makemyresumedb
    ports:
      - ${APP_PORT}:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${PASSWORD}
      MSSQL_PID: Express